CREATE PROC usp_SelectProjectByNm
(
	@NM_PRO VARCHAR(2000)
)
AS
SET NOCOUNT ON;

SELECT NO_PRO, CD_COUNTRY, DS_PRO_STATUS, DS_PTMOA, FG_DEL, ID_ATTACH, DT_REG_FST
FROM TBS_HTMLTEST
WHERE NM_PRO = @NM_PRO;
GO