CREATE PROC usp_InsertProject
(
	@NM_PRO VARCHAR(2000)
	,@NO_PRO VARCHAR(200)
	,@CD_COUNTRY VARCHAR(50)
	,@DS_PRO_STATUS VARCHAR(50)
	,@DS_PTMOA VARCHAR(50)
	,@DS_SOFA VARCHAR(max)
	,@FG_DEL VARCHAR(5)
	,@ID_ATTACH VARCHAR(500)
)
AS

	INSERT INTO TBS_HTMLTEST(NM_PRO, NO_PRO, CD_COUNTRY, DS_PRO_STATUS, DS_PTMOA, DS_SOFA, FG_DEL, ID_ATTACH)
	VALUES(@NM_PRO, @NO_PRO, @CD_COUNTRY, @DS_PRO_STATUS, @DS_PTMOA, @DS_SOFA, @FG_DEL, @ID_ATTACH);

GO

